Fix `use_device` not set correctly (#18)
* fix use_device not being set due to operator precedence

* add test to make sure StructOptimizer passes device to model correctly

* fix test

* fix tests take 2 and run on tests in matrix strategy for OS: [ubuntu-latest, macos-latest, windows-latest]

* guard against AttributeError: module 'torch.backends' has no attribute 'mps' on non-macOS

* only pin deps downward

* remove deps list from readme, people can always check pyproject.toml for the actual source of truth

* fix readme usage subsection heading levels

* format readme code snippets