v0.2.2
remove pymatgen down pin in pyproject.toml to fix spurious atomate2 dep resolution error

ERROR: Cannot install atomate2 and atomate2[strict,tests]==0.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    atomate2[strict,tests] 0.0.1 depends on pymatgen>=2023.10.4
    atomate2[strict,tests] 0.0.1 depends on pymatgen==2023.10.4; extra == "strict"
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    chgnet 0.2.1 depends on pymatgen>=2023.5.31
    emmet-core 0.70.0 depends on pymatgen>=2023.10.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict