Run `cibuildwheel` on Apple silicon to publish pre-compiled macOS ARM binaries (#78)
* run cibuildwheel on Apple silicon

* fix typo

* add option to release to TestPyPI

* run CI tests on macos-latest-xlarge

hopefully fixes

RuntimeError: MPS backend out of memory (MPS allocated: 0 bytes, other allocations: 0 bytes, max allowed: 1.70 GB). Tried to allocate 0 bytes on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

* pypa/cibuildwheel set CIBW_ARCHS_MACOS: universal2